<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\izzzz\OneDrive\Рабочий стол\ПиОГИ\MainWindow.xaml.cs" Link="MainWindow.xaml.cs" />
  </ItemGroup>

</Project>
